apiVersion: apps/v1
kind: Deployment

metadata:
  name: shoestore

spec:
  replicas: 1

  selector:
    matchLabels:
      app: shoestore

  template:
    metadata:
      labels:
        app: shoestore

    spec:
      containers:
      - name: shoestore
        image: my-apache
        imagePullPolicy: Never

        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: shoestore
spec:
  selector:
    app: shoestore
  ports:
  - port: 80
    targetPort: 80
    
