apiVersion: apps/v1
kind: Deployment

metadata:
  name: shoestore1

spec:
  replicas: 1

  selector:
    matchLabels:
      app: shoestore1

  template:
    metadata:
      labels:
        app: shoestore1

    spec:
      containers:
      - name: shoestore1
        image: shoestore:5
        imagePullPolicy: Never

        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: shoestore1
spec:
  selector:
    app: shoestore1
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  type: NodePort